### ISSUE TITLE
Does not compile on 1.43.0

### ISSUE THREAD

**Issue by piegamesde** [leod/pareen#8]
I just ran `rustup update` and now my application won't compile anymore:

```
error[E0308]: mismatched types
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pareen-0.2.2/src/lib.rs:135:14
    |
95  | impl<F> Anim<F>
    |      - this type parameter
...
135 |         Self(&self.0)
    |              ^^^^^^^
    |              |
    |              expected type parameter `F`, found `&F`
    |              help: consider removing the borrow: `self.0`
    |
    = note: expected type parameter `F`
                    found reference `&F`
    = help: type parameters must be constrained to match other types
    = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

error[E0308]: mismatched types
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pareen-0.2.2/src/lib.rs:135:9
    |
95  | impl<F> Anim<F>
    |      - this type parameter
...
135 |         Self(&self.0)
    |         ^^^^^^^^^^^^^ expected `&F`, found type parameter `F`
    |
    = note: expected struct `Anim<&F>`
               found struct `Anim<F>`
    = help: type parameters must be constrained to match other types
    = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `pareen`.
```

**Comment by leod** [comment]
Thank you for reporting this issue! I believe this has been fixed in #7, but I had not published a new version yet.

I've published version 0.2.3 now, hopefully this will fix the issue for you.

**Comment by piegamesde** [comment]
Thank you.
